apiVersion: v1
kind: ConfigMap
metadata:
  name: cosign-public-keys
  namespace: kyverno
data:
  cosign.pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE4yv/XBgduJhwsAM1rACSrUd3IE4L
    bvwZBNuZPbi05dXwChYP9zXfD8FGCZj+uWtnUeror0nZLb76Wp0CFK0/4g==
    -----END PUBLIC KEY-----

