apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: votechain
  labels:
    app: auth
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        tier: backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "auth-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/auth"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/auth" -}}
          export TOKEN_SECRET="{{ .Data.data.TOKEN_SECRET }}"
          {{- end }}
    spec:
      serviceAccountName: auth-sa
      containers:
        - name: auth
          image: votechain/auth:latest
          imagePullPolicy: Never
          command: ["/bin/sh","-c"]
          args:
            - . /vault/secrets/config && exec ./auth-service
          ports:
            - containerPort: 8002
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
