apiVersion: apps/v1
kind: Deployment
metadata:
  name: biometric-deployment
  namespace: votechain
  labels:
    app: biometric
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: biometric
  template:
    metadata:
      labels:
        app: biometric
        tier: backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "biometric-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/biometric"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/biometric" -}}
          export BIOMETRIC_PEPPER="{{ .Data.data.BIOMETRIC_PEPPER }}"
          {{- end }}
    spec:
      serviceAccountName: biometric-sa
      containers:
        - name: biometric
          image: votechain/biometric:latest
          imagePullPolicy: Never
          command: ["/bin/sh","-c"]
          args:
            - . /vault/secrets/config && exec uvicorn main:app --host 0.0.0.0 --port 8001
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
