apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: votechain
  labels:
    app: vote
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
        tier: backend
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vote-role"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/vote"
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "secret/data/vote" -}}
          export VOTE_SECRET="{{ .Data.data.JWT_SECRET }}"
          export API_KEY="{{ .Data.data.API_KEY }}"
          {{- end }}
    spec:
      serviceAccountName: vote-sa
      containers:
        - name: vote
          image: votechain/vote:latest
          imagePullPolicy: Never
          command: ["/bin/sh","-c"]
          args:
            - source /vault/secrets/config && node index.js
          ports:
            - containerPort: 8003
          env:
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: votechain-config
                  key: AUTH_SERVICE_URL
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 10
