apiVersion: v1
kind: Secret
metadata:
  name: votechain-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  BIOMETRIC_PEPPER: {{ .Values.secrets.biometricPepper | b64enc }}
  TOKEN_SECRET: {{ .Values.secrets.tokenSecret | b64enc }}
  VOTE_SECRET: {{ .Values.secrets.voteSecret | b64enc }}
