apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote-sa
  namespace: votechain
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-sa
  namespace: votechain
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: biometric-sa
  namespace: votechain
