apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: votechain
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP
