apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: votechain
  labels:
    app: vote
spec:
  selector:
    app: vote
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30003
  type: NodePort
